apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xappcaches.platform.lab
spec:
  group: platform.lab

  names:
    kind: XAppCache
    plural: xappcaches

  claimNames:
    kind: AppCache
    plural: appcaches

  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                appNamespace:
                  type: string
                  description: Namespace onde o Redis será implantado e o Secret de conexão criado
              required:
                - appNamespace
