apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apis-appcache
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: system
  source:
    repoURL: https://github.com/TourinhoM/platform-apis
    targetRevision: main
    path: appcache
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
